apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: app-service
  template:
    metadata:
      labels:
        app: app-service
    spec:
      containers:
        - name: app-service
          image: jodyys/government-kuyukiland-app-service:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 4002
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  ports:
    - port: 4002
  selector:
    app: app-service