events {}

http {
  server {
    listen 80;

    location / {
      proxy_pass http://frontend:3000;
    }

    location /auth/ {
      proxy_pass http://auth-service:4001/;
    }

    location /app/ {
      proxy_pass http://app-service:4002/;
    }

    location /ai/ {
      proxy_pass http://ai-service:4003/;
    }
  }
}